on:
    workflow_dispatch:
    release:
      types: [published]

jobs:
    build:
        name: Build binaries
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
              with:
                submodules: recursive
            - name: Mount Bazel Cache
              uses: actions/cache@v4
              env:
                cache-name: bazel_cache
              with:
                path: /home/runner/.cache/bazel
                key: bazel_test
            - name: setup
              run: |
                sudo ./ci/setup_ci_environment.sh
                sudo ./ci/install_bazelisk.sh
            - name: run tests
              run: ./ci/do_ci.sh bazel.test